name: pnpm-install
description: Install Node, PNPM and dependencies
runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 6.17.0
    - name: Install Node
      uses: actions/setup-node@v2
      with:
        node-version: 14
        cache: pnpm
    - run: pnpm i --frozen-lockfile
      shell: bash
